# Generated by Django 3.2 on 2021-04-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210422_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='mainapp.exam'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='mainapp.student'),
        ),
    ]
